server:
  port: ${PORT:8082}

spring:
  application:
    name: inventory-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/inventory_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: UTC

app:
  jwt:
    secret: ${APP_JWT_SECRET:01234567890123456789012345678901papeleria}
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:4200}
