options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1
  _REPOSITORY: papeleria
  _TAG: latest

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - auth-service/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/auth-service:${_TAG}
      - auth-service

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - inventory-service/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/inventory-service:${_TAG}
      - inventory-service

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - sales-service/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/sales-service:${_TAG}
      - sales-service

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - frontend/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:${_TAG}
      - frontend

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/auth-service:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/inventory-service:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/sales-service:${_TAG}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/frontend:${_TAG}
